<div data-bind="scope: 'notificationComponent'">
	<div data-bind="foreach: notifications ">
		<div data-bind="style: {'background-color': background_color}">
			<div data-bind="html: content"></div>
		</div>
	</div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "notificationComponent": {
                    "component": "Uvarov_Bar/js/view/notification"
                }
            }
        }
    }
}

</script>